// backend/controllers/chatbotmessage.js

// ⚠️ This is the final self-contained version.
export const message = async (req, res) => {
  // ⚠️ Ensure your FULL array is pasted here (178 lines total from previous context).
  const botResponses=[
    "hello?: hello how may i help you",
    "What percentage of the body's total energy does the human brain use?: The human brain uses about 20% of the body's total energy.",
    "Is the Great Wall of China visible from space with the naked eye?: The Great Wall of China is not visible from space with the naked eye.",
    "When was the first computer mouse invented and what was it made of?: The first computer mouse was invented in 1964 and was made of wood.",
    "How many hearts do octopuses have and what do they do?: Octopuses have three hearts: two pump blood to the gills, and one to the rest of the body.",
    "How long did the shortest tennis match in history last?: The shortest tennis match in history lasted only 20 minutes.",
    "Why is a day on Venus longer than its year?: A day on Venus is longer than its year due to its slow rotation.",
    "Does honey ever spoil, and where has edible honey been found?: Honey never spoils; archaeologists have found edible honey in ancient Egyptian tombs.",
    "How long have sharks been around compared to trees?: Sharks have been around longer than trees, dating back over 400 million years.",
    "Why does the Mona Lisa have no eyebrows?: The Mona Lisa has no eyebrows; they were painted over in later restorations.",
    "How many time zones does Russia span?: Russia spans 11 time zones, more than any other country.",
    "What ability do dolphins have that shows self-awareness?: Dolphins can recognize themselves in mirrors, showing self-awareness.",
    "How often does lightning strike the Earth?: Lightning strikes the Earth about 100 times per second.",
    "How high can penguins jump out of the water?: Penguins can jump as high as 6 meters out of the water.",
    "What was the internet originally called and when?: The internet was originally called ARPANET in 1969.",
    "How many active volcanoes are there on Earth?: There are over 1,500 active volcanoes on Earth.",
    "What is a group of flamingos called?: A group of flamingos is called a flamboyance.",
    "How long did the shortest war in history last?: The shortest war in history lasted only 38-45 minutes.",
    "Are bananas berries, and are strawberries?: Bananas are berries, but strawberries are not.",
    "How many colors can the human eye distinguish?: The human eye can distinguish about 10 million colors.",
    "How hot is a bolt of lightning compared to the sun's surface?: A bolt of lightning is five times hotter than the surface of the sun.",
    "Why do octopuses have blue blood?: Octopuses have blue blood due to copper-based hemocyanin.",
    "When was the first email sent and by whom?: The first email was sent in 1971 by Ray Tomlinson.",
    "What shape is wombat poop?: Wombat poop is cube-shaped.",
    "How old is the universe?: The universe is about 13.8 billion years old.",
    "How long is a day on Mercury in Earth days?: A day on Mercury lasts 176 Earth days.",
    "What is the largest desert in the world?: The largest desert in the world is Antarctica.",
    "How do butterflies taste?: Butterflies taste with their feet.",
    "Who was the first computer programmer?: The first computer programmer was Ada Lovelace.",
    "Where is a shrimp's heart located?: A shrimp's heart is in its head.",
    "How fast is the moon moving away from Earth?: The moon is moving away from Earth at about 3.8 cm per year.",
    "How many neck vertebrae do giraffes have compared to humans?: Giraffes have the same number of neck vertebrae as humans: seven.",
    "What was the first webcam used for?: The first webcam was used to monitor a coffee pot.",
    "What is a group of owls called?: A group of owls is called a parliament.",
    "What is the deepest point in the ocean and how deep is it?: The deepest point in the ocean is the Mariana Trench, about 11 km deep.",
    "How does Cleopatra's time relate to the Moon landing and the Great Pyramid?: Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.",
    "How fast does a sneeze travel?: A sneeze travels at speeds up to 100 mph.",
    "What was the first video game and when was it released?: The first video game was Pong, released in 1972.",
    "How long can sloths hold their breath underwater?: Sloths can hold their breath underwater for up to 40 minutes.",
    "How many bones does the human body have?: The human body has 206 bones.",
    "How long is a year on Jupiter in Earth years?: A year on Jupiter is about 12 Earth years.",
    "What was the largest animal ever?: The largest animal ever was the blue whale.",
    "How many muscles control a cat's ears?: Cats have over 20 muscles that control their ears.",
    "What was the first smartphone and when?: The first smartphone was the IBM Simon Personal Communicator in 1994.",
    "What is a group of rhinos called?: A group of rhinos is called a crash.",
    "Is the Sahara Desert expanding?: The Sahara Desert is expanding.",
    "Can frogs freeze solid and survive?: Frogs can freeze solid and survive.",
    "What was the first computer bug and when?: The first computer bug was an actual bug in 1947.",
    "How do elephants hear?: Elephants can hear with their feet.",
    "What is the temperature of the sun's core?: The sun's core temperature is about 15 million degrees Celsius.",
    "How long is a day on Mars?: A day on Mars is about 24 hours and 37 minutes.",
    "What is the longest English word without a vowel?: The longest English word without a vowel is 'rhythms'.",
    "Can ostriches run faster than horses?: Ostriches can run faster than horses.",
    "When was the first fax machine invented?: The first fax machine was invented in 1843.",
    "What is a group of jellyfish called?: A group of jellyfish is called a smack.",
    "What is the largest ocean on Earth?: The Pacific Ocean is the largest ocean on Earth.",
    "Can bees recognize human faces?: Bees can recognize human faces.",
    "When was the first ATM installed?: The first ATM was installed in 1967.",
    "How many hours a day do koalas sleep?: Koalas sleep up to 22 hours a day.",
    "How many base pairs are in the human genome?: The human genome has about 3 billion base pairs.",
    "How long is a year on Neptune in Earth years?: A year on Neptune is about 165 Earth years.",
    "What is the smallest bone in the human body?: The smallest bone in the human body is in the ear.",
    "What do pandas eat almost exclusively?: Pandas eat bamboo almost exclusively.",
    "When was the first mobile phone call made?: The first mobile phone call was made in 1973.",
    "What is a group of kangaroos called?: A group of kangaroos is called a mob.",
    "What percentage of the world's oxygen does the Amazon Rainforest produce?: The Amazon Rainforest produces 20% of the world's oxygen.",
    "How long can snails sleep?: Snails can sleep for three years.",
    "When was the first computer virus created?: The first computer virus was created in 1983.",
    "How long can whale songs last?: Whales sing songs that can last up to 30 minutes.",
    "What is the hottest temperature ever recorded on Earth?: The hottest temperature ever recorded on Earth was 56.7°C.",
    "How long is a day on Pluto?: A day on Pluto is about 153 hours.",
    "What is the longest river in the world?: The longest river in the world is the Nile.",
    "Can owls move their eyes?: Owls cannot move their eyes; they swivel their heads.",
    "When was the first laser built?: The first laser was built in 1960.",
    "What is a group of porcupines called?: A group of porcupines is called a prickle.",
    "What is the lowest point on Earth?: The Dead Sea is the lowest point on Earth.",
    "What were lobsters once considered?: Lobsters were once considered prison food.",
    "When was the first website created?: The first website was created in 1991.",
    "What are hummingbirds the only birds that can do?: Hummingbirds are the only birds that can fly backwards.",
    "Does the human body contain enough iron to make a small nail?: The human body contains enough iron to make a small nail.",
    "How long is a year on Uranus in Earth years?: A year on Uranus is about 84 Earth years.",
    "What is the tallest mountain and its height?: The tallest mountain is Everest at 8,848 meters.",
    "Do raccoons wash their food before eating?: Raccoons wash their food before eating.",
    "When was the first digital camera invented?: The first digital camera was invented in 1975.",
    "What is a group of zebras called?: A group of zebras is called a dazzle.",
    "Is the Bermuda Triangle officially recognized as dangerous?: The Bermuda Triangle is not officially recognized as dangerous.",
    "Can starfish regenerate lost arms?: Starfish can regenerate lost arms.",
    "What was the first social media site and when?: The first social media site was Six Degrees in 1997.",
    "How fast can cheetahs accelerate?: Cheetahs can accelerate from 0 to 60 mph in 3 seconds.",
    "What is the coldest temperature ever recorded?: The coldest temperature ever was -89.2°C in Antarctica.",
    "How long is a day on Saturn?: A day on Saturn is about 10.7 hours.",
    "What is the largest lake?: The largest lake is the Caspian Sea.",
    "What are bats the only mammals that can do?: Bats are the only mammals that can fly.",
    "When was the first GPS satellite launched?: The first GPS satellite was launched in 1978.",
    "What is a group of lions called?: A group of lions is called a pride.",
    "What is the coldest desert?: The Gobi Desert is the coldest desert.",
    "How long can sea turtles hold their breath?: Sea turtles can hold their breath for up to 7 hours.",
    "When was the first emoji created?: The first emoji was created in 1999.",
    "Can gorillas learn sign language?: Gorillas can learn sign language.",
    "What is the driest place on Earth?: The driest place on Earth is the Atacama Desert.",
    "How long is a year on Earth?: A year on Earth is 365.25 days.",
    "How many times does the human heart beat in a day?: The human heart beats about 100,000 times a day.",
    "When was the first airplane flight?: The first airplane flight was in 1903.",
    "What is a group of wolves called?: A group of wolves is called a pack.",
    "In which direction does the Nile River flow?: The Nile River flows northward.",
    "Can crows use tools?: Crows can use tools.",
    "When was the first microwave oven invented?: The first microwave oven was invented in 1945.",
    "What is a group of hyenas called?: A group of hyenas is called a cackle.",
    "What desert is home to meerkats?: The Kalahari Desert is home to meerkats.",
    "How long can turtles live?: Turtles can live over 100 years.",
    "What was the first internet search engine and when?: The first internet search engine was Archie in 1990.",
    "Can leopards climb trees with their prey?: Leopards can climb trees with their prey.",
    "What is the wettest place on Earth?: The wettest place is Mawsynram, India.",
    "How long is a day on the Moon?: A day on the Moon is about 29.5 Earth days.",
    "What is the longest word in English?: The longest word in English is pneumonoultramicroscopicsilicovolcanoconiosis.",
    "Can rabbits see behind them without turning their heads?: Rabbits can see behind them without turning their heads.",
    "When was the first refrigerator invented?: The first refrigerator was invented in 1805.",
    "What is a group of peacocks called?: A group of peacocks is called an ostentation.",
    "What desert has Saguaro cacti?: The Sonoran Desert has Saguaro cacti.",
    "Can salamanders regenerate limbs?: Salamanders can regenerate limbs.",
    "When was the first barcode scanned?: The first barcode was scanned in 1974.",
    "Can hippos run faster than humans?: Hippos can run faster than humans.",
    "What is the windiest place on Earth?: The windiest place is Commonwealth Bay, Antarctica.",
    "How long is a year on Ceres?: A year on Ceres is about 4.6 Earth years.",
    "What is the shortest mammal?: The shortest mammal is the bumblebee bat.",
    "When was the first radio broadcast?: The first radio broadcast was in 1906.",
    "What is a group of badgers called?: A group of badgers is called a cete.",
    "What is the Taklamakan Desert known as?: The Taklamakan Desert is known as the Sea of Death.",
    "Can eagles see ultraviolet light?: Eagles can see ultraviolet light.",
    "What was the first calculator?: The first calculator was the abacus.",
    "What is a group of vultures called?: A group of vultures is called a wake.",
    "What is the hottest place on Earth?: The Lut Desert is the hottest place on Earth.",
    "Do axolotls ever fully metamorphose?: Axolotls never fully metamorphose.",
    "When was the first video call?: The first video call was in 1964.",
    "Do lynxes have excellent night vision?: Lynxes have excellent night vision.",
    "What is the saltiest sea?: The saltiest sea is the Dead Sea.",
    "How long is a day on Io?: A day on Io is about 42.5 hours.",
    "What is the largest flower?: The largest flower is the Rafflesia.",
    "When was the first typewriter patented?: The first typewriter was patented in 1868.",
    "What is a group of swans called?: A group of swans is called a bevy.",
    "What desert is in Australia?: The Simpson Desert is in Australia.",
    "Can newts regrow eyes?: Newts can regrow eyes.",
    "When was the first CD released?: The first CD was released in 1982.",
    "How fast can falcons dive?: Falcons can dive at 240 mph.",
    "What is the coldest sea?: The coldest sea is the Arctic Ocean.",
    "How long is a year on Pluto?: A year on Pluto is about 248 Earth years.",
    "What is the smallest country?: The smallest country is Vatican City.",
    "When was the first telescope invented?: The first telescope was invented in 1608.",
    "What is a group of finches called?: A group of finches is called a charm.",
    "What desert is in India?: The Thar Desert is in India.",
    "Can planarians regenerate their entire body?: Planarians can regenerate their entire body.",
    "When was the first MP3 player released?: The first MP3 player was released in 1998.",
    "What are orcas?: Orcas are the largest dolphins.",
    "What is the highest waterfall?: The highest waterfall is Angel Falls.",
    "How long is a day on Titan?: A day on Titan is about 16 days.",
    "What is the longest snake?: The longest snake is the reticulated python.",
    "When was the first steam engine invented?: The first steam engine was in 1769.",
    "What is a group of sparrows called?: A group of sparrows is called a host.",
    "What desert has Joshua trees?: The Mojave Desert has Joshua trees.",
    "Can hydras regenerate from fragments?: Hydras can regenerate from fragments.",
    "When was the first floppy disk invented?: The first floppy disk was in 1971.",
    "What are peregrine falcons known for?: Peregrine falcons are the fastest birds.",
    "What is the deepest lake?: The deepest lake is Lake Baikal.",
    "How long is a year on Eris?: A year on Eris is about 557 Earth years.",
    "What is the smallest bird?: The smallest bird is the bee hummingbird.",
    "When was the first telephone invented?: The first telephone was in 1876.",
    "What is a group of robins called?: A group of robins is called a round.",
    "What is the oldest desert?: The Namib Desert is the oldest.",
    "Can sea cucumbers eject their intestines?: Sea cucumbers can eject their intestines.",
    "When was the first VCR invented?: The first VCR was in 1972.",
    "What do condors have?: Condors have the largest wingspan.",
    "What is the saltiest lake?: The saltiest lake is Lake Assal.",
    "How long is a day on Europa?: A day on Europa is about 3.5 days.",
    "What is the largest tree?: The largest tree is Hyperion.",
    "When was the first sewing machine invented?: The first sewing machine was in 1790.",
    "What is a group of starlings called?: A group of starlings is called a murmuration.",
    "What is the Patagonian Desert known for?: The Patagonian Desert is windy.",
    "What is Mount Everest known for?: Being the highest mountain above sea level.",
    "What is the Amazon River known for?: Being the world's most voluminous river.",
    "What is the Suez Canal known for?: Connecting the Mediterranean Sea to the Red Sea.",
    "What is the Mariana Trench known for?: Containing the deepest point on Earth.",
    "What is the Dead Sea known for?: Its high salt concentration that causes flotation.",
    "What is the Sahara Desert known for?: Being the world's largest hot desert.",
    "What is Iceland known for?: Its abundance of geysers and hot springs.",
    "What is the Strait of Gibraltar known for?: Connecting the Atlantic Ocean and the Mediterranean Sea.",
    "What is the Serengeti National Park known for?: Hosting the annual Great Migration of wildebeest.",
    "What is Mount Fuji known for?: Being Japan's highest and most sacred peak.",
    "What is the Grand Canyon known for?: Its vast scale and exposed geological history.",
    "What is Venice known for?: Its network of canals used instead of roads.",
    "What is the Atacama Desert known for?: Being the driest non-polar desert on Earth.",
    "What is the Panama Canal known for?: Linking the Atlantic and Pacific Oceans for maritime trade.",
    "What is Angel Falls known for?: Being the world's highest uninterrupted waterfall.",
    "What is Australia's Outback known for?: Its vast, remote, and sparsely populated interior.",
    "What is the Swiss Alps known for?: Its dramatic jagged peaks and iconic Matterhorn mountain.",
    "What is the Nile River known for?: Being the longest river in the world.",
    "What is Santorini known for?: Its white and blue cliffside architecture.",
    "What is the Galápagos Islands known for?: Its unique species studied by Charles Darwin.",
    "What is the Himalayas known for?: Housing the world's highest mountains, including Everest.",
    "What is Madagascar known for?: Being home to thousands of species found nowhere else, like the lemur.",
    "What is the Yellow Sea known for?: The yellowish color caused by sand and silt from the Yellow River.",
    "What is the Danube River known for?: Flowing through ten countries in Central and Eastern Europe.",
    "What is Greenland known for?: Being the world's largest island.",
    "What is the Gobi Desert known for?: Its role in the ancient Silk Road trade route.",
    "What is Kilimanjaro known for?: Being Africa's highest mountain and a dormant volcano.",
    "What is Kyoto known for?: Its numerous classic Buddhist temples, gardens, and imperial palaces.",
    "What is the Iberian Peninsula known for?: Containing the countries of Spain and Portugal.",
    "What is the Bay of Bengal known for?: Being the largest bay in the world.",
    "What is the Black Forest known for?: Its dark, dense evergreen forests and traditional clock-making.",
    "What is Machu Picchu known for?: Being an ancient, well-preserved Inca citadel.",
    "What is Yosemite National Park known for?: Its granite cliffs like El Capitan and waterfalls.",
    "What is the Bermuda Triangle known for?: Being the site of alleged mysterious disappearances of ships and planes.",
    "What is Timbuktu known for?: Historically being a major center for Islamic scholarship and trade.",
    "What is Java known for?: Being the most populous island in the world.",
    "What is the Great Salt Lake known for?: Being the largest saltwater lake in the Western Hemisphere.",
    "What is the Baltic Sea known for?: Its low salinity and shallow depths.",
    "What is Fiji known for?: Its friendly culture and picturesque coral reefs.",
    "What is Patagonia known for?: Being a vast, windy, cold desert plateau in South America.",
    "What is Petra, Jordan known for?: Its ancient rock-cut architecture and Treasury building.",
    "What is the Khyber Pass known for?: Its historical strategic importance in connecting Afghanistan and Pakistan.",
    "What is the Philippines known for?: Being an archipelago composed of over 7,000 islands.",
    "What is the Okavango Delta known for?: Being an inland river delta that floods seasonally.",
    "What is the Serengeti known for?: The annual mass migration of wildlife.",
    "What is Tokyo known for?: Being the most populous metropolitan area in the world.",
    "What is Sicily known for?: Being the largest island in the Mediterranean Sea.",
    "What is Cappadocia known for?: Its distinctive tall, cone-shaped rock formations.",
    "What is the Ganges River known for?: Being a sacred river in Hinduism.",

    // --- SCIENCE & TECHNOLOGY (51-100) ---
    "What is the speed of light known for?: Being the fastest speed anything can travel in a vacuum.",
    "What is the nucleus of an atom known for?: Containing the majority of the atom's mass.",
    "What is DNA known for?: Carrying the genetic instructions for development and function.",
    "What is gravity known for?: Being the force that pulls masses toward each other.",
    "What is a black hole known for?: Having a gravitational pull so strong that nothing, not even light, can escape.",
    "What is photosynthesis known for?: Converting light energy into chemical energy in plants.",
    "What is the periodic table known for?: Organizing all known chemical elements by atomic number.",
    "What is the Higgs boson known for?: Giving elementary particles their mass.",
    "What is the pH scale known for?: Measuring the acidity or basicity of an aqueous solution.",
    "What is the Doppler Effect known for?: Explaining the change in wave frequency relative to an observer.",
    "What is the immune system known for?: Defending the body against infectious disease.",
    "What is the ozone layer known for?: Absorbing most of the Sun's harmful ultraviolet radiation.",
    "What is Newton's First Law known for?: Stating that an object in motion stays in motion unless acted upon by a force.",
    "What is a compiler known for?: Translating high-level code into machine code.",
    "What is the nervous system known for?: Transmitting signals between different parts of the body.",
    "What is the Kelvin scale known for?: Being an absolute thermodynamic temperature scale.",
    "What is the theory of relativity known for?: Describing how gravity and space-time are related.",
    "What is an enzyme known for?: Speeding up chemical reactions in living organisms.",
    "What is the metric system known for?: Being a decimal system of measurement used worldwide.",
    "What is a superconductor known for?: Conducting electricity with zero resistance.",
    "What is the Bernoulli principle known for?: Explaining how lift is generated on an airplane wing.",
    "What is blockchain known for?: Being a decentralized, distributed ledger technology.",
    "What is the lithosphere known for?: Comprising the Earth's crust and the uppermost mantle.",
    "What is the Big Bang Theory known for?: Explaining the origin and expansion of the universe.",
    "What is penicillin known for?: Being the first widely used antibiotic.",
    "What is thermal expansion known for?: The tendency of matter to change volume in response to temperature change.",
    "What is artificial intelligence (AI) known for?: Simulating human intelligence in machines.",
    "What is the circulatory system known for?: Pumping blood throughout the body.",
    "What is nuclear fission known for?: The splitting of an atomic nucleus to release energy.",
    "What is binary code known for?: Using only two digits, 0 and 1, to represent data.",
    "What is an exothermic reaction known for?: Releasing energy, usually in the form of heat or light.",
    "What is the Kuiper Belt known for?: Being a region of the solar system beyond Neptune containing small bodies.",
    "What is the principle of buoyancy known for?: Explaining why objects float.",
    "What is CRISPR known for?: Being a powerful tool for editing genomes.",
    "What is kinetic energy known for?: Being the energy possessed by an object due to its motion.",
    "What is the Fibonacci sequence known for?: Each number being the sum of the two preceding ones.",
    "What is carbon dating known for?: Determining the age of organic materials.",
    "What is virtualization known for?: Creating a simulated, rather than physical, version of a computing resource.",
    "What is refraction known for?: The bending of light as it passes from one medium to another.",
    "What is evolution known for?: Explaining how species change over successive generations.",
    "What is a satellite known for?: Orbiting a celestial body or planet.",
    "What is diffusion known for?: The net movement of molecules from a high concentration area to a low concentration area.",
    "What is a firewall known for?: Monitoring and controlling incoming and outgoing network traffic.",
    "What is an alloy known for?: Being a mixture of two or more elements, where at least one is a metal.",
    "What is general relativity known for?: Incorporating gravity into Einstein's framework of space and time.",
    "What is JavaScript known for?: Being the programming language that makes web pages interactive.",
    "What is the greenhouse effect known for?: Trapping heat in the atmosphere to warm the planet.",
    "What is electrolysis known for?: Using electricity to drive a non-spontaneous chemical reaction.",
    "What is the World Wide Web known for?: Being the primary tool used by billions of people to interact on the Internet.",
    "What is the Hubble Space Telescope known for?: Providing stunning, high-resolution images of deep space.",
    
    // --- HISTORY & POLITICS (101-150) ---
    "What is the Roman Empire known for?: Its extensive road network and lasting legal systems.",
    "What is the Rosetta Stone known for?: Providing the key to deciphering Egyptian hieroglyphs.",
    "What is the French Revolution known for?: Overthrowing the monarchy and establishing a republic.",
    "What is the Cold War known for?: The political tension and military rivalry between the US and the Soviet Union.",
    "What is the Magna Carta known for?: Limiting the power of the English monarch.",
    "What is the Byzantine Empire known for?: Preserving Greek and Roman culture for a thousand years after Rome fell.",
    "What is the Black Death known for?: The devastating pandemic that swept through Europe in the 14th century.",
    "What is the Industrial Revolution known for?: The shift from hand production to machine production.",
    "What is the Berlin Wall known for?: Symbolizing the Iron Curtain division during the Cold War.",
    "What is the Civil Rights Movement known for?: Advocating for legal equality for African Americans.",
    "What is the Renaissance known for?: The period of great cultural and artistic revival in Europe.",
    "What is the Battle of Gettysburg known for?: Being the turning point of the American Civil War.",
    "What is the Age of Exploration known for?: European navigators discovering and mapping new lands.",
    "What is the Ottoman Empire known for?: Lasting for over six centuries and controlling much of Southeast Europe and North Africa.",
    "What is the Vietnam War known for?: Being the first war widely televised.",
    "What is the Enlightenment known for?: Emphasizing reason, individualism, and challenging traditional authority.",
    "What is the Apollo 11 mission known for?: Successfully landing the first humans on the Moon.",
    "What is the Silk Road known for?: The ancient network of trade routes connecting East and West.",
    "What is the Cuban Missile Crisis known for?: Being the closest the world has ever come to nuclear war.",
    "What is the Holocaust known for?: The genocide of six million Jews by the Nazi regime.",
    "What is the League of Nations known for?: Being the first intergovernmental organization to promote world peace.",
    "What is the Stone Age known for?: The widespread use of stone for tools.",
    "What is the Declaration of Independence known for?: Announcing that the thirteen American colonies were independent from Great Britain.",
    "What is the Meiji Restoration known for?: Rapidly modernizing and industrializing Japan.",
    "What is the fall of the Bastille known for?: The symbolic start of the French Revolution.",
    "What is the Code of Hammurabi known for?: Being one of the earliest and most complete written legal codes.",
    "What is the Crusades known for?: The series of religious wars sanctioned by the Latin Church.",
    "What is the Great Wall of China known for?: Being a massive series of fortifications built to protect the northern borders.",
    "What is the Boston Tea Party known for?: American colonists protesting British taxation without representation.",
    "What is the Space Race known for?: The 20th-century competition between the US and USSR to achieve spaceflight superiority.",
    "What is the Spanish Armada known for?: Its defeat in 1588 marking a major turning point in naval power.",
    "What is the invention of the wheel known for?: Revolutionizing transport and farming.",
    "What is the Neolithic Revolution known for?: The shift from hunting/gathering to settled agriculture.",
    "What is apartheid known for?: The system of institutionalized racial segregation and discrimination in South Africa.",
    "What is the Berlin Airlift known for?: The Western Allies flying supplies into West Berlin after the Soviets blockaded it.",
    "What is the Panama Hat known for?: Being misnamed, as it originates from Ecuador.",
    "What is the Treaty of Versailles known for?: Officially ending World War I.",
    "What is the Golden Age of Islam known for?: Major advancements in science, mathematics, and philosophy.",
    "What is the Boxer Rebellion known for?: An anti-foreign, anti-colonial, and anti-Christian uprising in China.",
    "What is the Watergate Scandal known for?: Leading to the resignation of U.S. President Richard Nixon.",
    "What is the invention of the printing press known for?: Revolutionizing communication by enabling mass production of books.",
    "What is the Punic Wars known for?: The massive conflicts between Rome and Carthage.",
    "What is the Oregon Trail known for?: The historic route used by 19th-century American pioneers to migrate west.",
    "What is the Ming Dynasty known for?: Building the Forbidden City and massive naval expeditions.",
    "What is the Marshall Plan known for?: The US program to aid Western Europe rebuild after World War II.",
    "What is feudalism known for?: A social system based on mutual obligation between lords and vassals.",
    "What is the Battle of Thermopylae known for?: A small force of Spartans holding off a much larger Persian army.",
    "What is the fall of Constantinople known for?: Marking the final collapse of the Byzantine Empire in 1453.",
    "What is the Great Depression known for?: The severe worldwide economic downturn during the 1930s.",
    "What is the Abolitionist Movement known for?: Advocating for the end of slavery.",

    // --- ARTS & LITERATURE (151-200) ---
    "What is William Shakespeare known for?: Writing in Early Modern English and composing 38 plays.",
    "What is the Mona Lisa known for?: The subject's enigmatic smile and use of sfumato technique.",
    "What is Impressionism known for?: Focusing on capturing fleeting light and movement.",
    "What is the novel *1984* known for?: Popularizing concepts like Big Brother and thought police.",
    "What is a sonnet known for?: Being a 14-line poem written in iambic pentameter.",
    "What is the Louvre Museum known for?: Being the world's most-visited museum and housing the Mona Lisa.",
    "What is Gothic architecture known for?: Pointed arches, ribbed vaults, and flying buttresses.",
    "What is Frida Kahlo known for?: Her intense and symbolic self-portraits.",
    "What is the *Odyssey* known for?: Telling the story of Odysseus's ten-year journey home after the Trojan War.",
    "What is the Romantic movement known for?: Emphasizing emotion, individualism, and glorification of nature.",
    "What is Vincent van Gogh known for?: His highly expressive brushwork and vibrant colors.",
    "What is a fresco known for?: A wall-painting technique done on wet plaster.",
    "What is Pablo Picasso known for?: Co-founding the Cubist movement.",
    "What is *Moby Dick* known for?: The obsessive quest of Captain Ahab to hunt a white whale.",
    "What is Abstract Expressionism known for?: Emphasizing spontaneous, automatic, or subconscious creation.",
    "What is the Globe Theatre known for?: Being the London playhouse associated with William Shakespeare.",
    "What is Leo Tolstoy's *War and Peace* known for?: Its epic length and detailed historical account of the Napoleonic era.",
    "What is Pop Art known for?: Challenging fine art traditions by using imagery from popular and mass culture.",
    "What is Baroque music known for?: Its highly ornamented and elaborate style.",
    "What is Agatha Christie known for?: Being the best-selling fiction writer of all time.",
    "What is the *Statue of David* known for?: Being a marble masterpiece of the Renaissance sculpted by Michelangelo.",
    "What is a Limmerick known for?: A five-line humorous poem with a distinct AABBA rhyme scheme.",
    "What is Surrealism known for?: Creating uncanny and illogical scenes derived from dreams and the subconscious.",
    "What is *Hamlet* known for?: Containing the famous soliloquy, 'To be or not to be'.",
    "What is Jazz music known for?: Its strong tradition of improvisation and syncopated rhythms.",
    "What is *One Hundred Years of Solitude* known for?: Being a seminal work of magical realism.",
    "What is the Parthenon known for?: Being a former temple on the Athenian Acropolis dedicated to the goddess Athena.",
    "What is a biography known for?: Being a non-fiction account of someone's life written by another person.",
    "What is *The Starry Night* known for?: Its swirling, thick depiction of a night sky.",
    "What is the Dada movement known for?: Rejecting logic and reason in favor of nonsense and chaos.",
    "What is *The Great Gatsby* known for?: Exploring themes of decadence, idealism, and the American Dream.",
    "What is the Eiffel Tower known for?: Being built as the entrance arch for the 1889 World's Fair.",
    "What is a memoir known for?: Being an autobiographical form focusing on a specific period or event in the author's life.",
    "What is Tchaikovsky's *Swan Lake* known for?: Being one of the most technically challenging and iconic ballets.",
    "What is *A Sunday Afternoon on the Island of La Grande Jatte* known for?: Being painted using the technique of pointillism.",
    "What is *Don Quixote* known for?: Being one of the earliest and greatest modern novels.",
    "What is Minimalism known for?: Stripping art down to its essential characteristics.",
    "What is J.R.R. Tolkien's *The Hobbit* known for?: Serving as the prequel to *The Lord of the Rings* trilogy.",
    "What is the Sistine Chapel known for?: Its ceiling frescoes painted by Michelangelo.",
    "What is *The Raven* known for?: The famous refrain 'Nevermore.'",
    "What is photography known for?: Capturing and recording light on a light-sensitive material.",
    "What is the Harlem Renaissance known for?: The explosion of African American arts and culture in the 1920s.",
    "What is Classical music known for?: Its emphasis on clarity, balance, and formal structure.",
    "What is *Catch-22* known for?: Coining the term for a paradoxical no-win situation.",
    "What is Abstract Art known for?: Not representing objects from the external world.",
    "What is the *Iliad* known for?: Homer's account of the final year of the Trojan War.",
    "What is *The Thinker* known for?: Being Auguste Rodin's iconic bronze sculpture.",
    "What is Horror Vacui known for?: Filling the entire surface of a space with detail.",
    "What is *To Kill a Mockingbird* known for?: Exploring themes of racial injustice and loss of innocence in the American South.",
    "What is Surrealist Salvador Dalí known for?: His striking and bizarre dream-like imagery.",

    // --- POP CULTURE, MYTHOLOGY & MISC. (201-300) ---
    "What is the Kraken known for?: Being a mythical sea monster resembling a giant squid.",
    "What is James Bond known for?: The catchphrase 'Bond, James Bond' and his use of gadgets.",
    "What is Batman known for?: Protecting Gotham City without possessing any actual superpowers.",
    "What is Pandora's Box known for?: Releasing all the evils of the world, leaving only hope inside.",
    "What is the Oscars known for?: Being the highest film honor awarded by the Academy of Motion Picture Arts and Sciences.",
    "What is the concept of a 'meme' known for?: An idea or behavior that spreads rapidly through a culture.",
    "What is the Greek God Zeus known for?: Being the king of the gods and ruler of Mount Olympus.",
    "What is the Marvel Comics character Spider-Man known for?: His sense of responsibility expressed as 'With great power comes great responsibility.'",
    "What is the game of Chess known for?: Being a strategic board game where the objective is to checkmate the opponent's king.",
    "What is Pokémon known for?: The concept of collecting and battling fictional creatures.",
    "What is the Super Bowl known for?: Being the annual championship game of the National Football League (NFL).",
    "What is the Loch Ness Monster known for?: Being a supposed large animal inhabiting a lake in Scotland.",
    "What is the film *Citizen Kane* known for?: Its innovative narrative structure and cinematography.",
    "What is the phrase 'The show must go on' known for?: Emphasizing perseverance despite difficulties.",
    "What is the Philosopher's Stone known for?: An alchemical substance capable of turning base metals into gold.",
    "What is the game of Monopoly known for?: Trading and developing properties with the goal of bankrupting opponents.",
    "What is the rock band Queen known for?: Their lead singer Freddie Mercury and anthemic rock songs.",
    "What is *Star Wars* known for?: Popularizing the space opera genre and using groundbreaking special effects.",
    "What is the legend of King Arthur known for?: The sword Excalibur and the Knights of the Round Table.",
    "What is the Nobel Prize known for?: Recognizing achievements in physics, chemistry, medicine, literature, and peace.",
    "What is Halloween known for?: Trick-or-treating and wearing costumes.",
    "What is the Roman God Mars known for?: Being the god of war.",
    "What is the Internet known for?: The interconnected system of computer networks that use the standard Internet Protocol Suite.",
    "What is the Golden Gate Bridge known for?: Its signature International Orange color.",
    "What is the concept of Karma known for?: The sum of a person's actions determining their future state of existence.",
    "What is the film *The Godfather* known for?: Being a cinematic masterpiece about the Corleone crime family.",
    "What is Sherlock Holmes known for?: His brilliant use of deductive reasoning to solve crimes.",
    "What is the Olympic Games known for?: Being a leading international sporting event featuring summer and winter competitions.",
    "What is the Easter Island known for?: Its massive stone statues called moai.",
    "What is the mythological creature Griffin known for?: Having the head and wings of an eagle and the body of a lion.",
    "What is the video game *Tetris* known for?: Being a puzzle game based on manipulating falling geometric shapes.",
    "What is the Taj Mahal known for?: Being a magnificent white marble mausoleum built by Mughal emperor Shah Jahan.",
    "What is the acronym 'NASA' known for?: Standing for the National Aeronautics and Space Administration.",
    "What is the concept of 'Déjà vu' known for?: The illusion of having previously experienced something actually being encountered for the first time.",
    "What is the mythological figure Medusa known for?: Having snakes for hair and turning people to stone with her gaze.",
    "What is the game of Cricket known for?: Being one of the most popular sports in the Commonwealth countries.",
    "What is the music genre Hip Hop known for?: Its foundational elements of rapping, DJing, breakdancing, and graffiti art.",
    "What is the fictional continent Middle-earth known for?: Being the primary setting for *The Lord of the Rings*.",
    "What is the concept of 'The Butterfly Effect' known for?: A small initial change causing large differences in a later state.",
    "What is the mythological creature Phoenix known for?: Dying in flames and rising renewed from the ashes.",
    "What is the Academy Award known for?: Its gold-plated trophy of a stylized human figure.",
    "What is the video game *Minecraft* known for?: Its block-based, procedurally generated 3D world.",
    "What is the beverage Coca-Cola known for?: Being the world's best-selling soft drink.",
    "What is the city of Las Vegas known for?: Its huge concentration of casinos and entertainment venues.",
    "What is the sport of Rugby known for?: The unique oval-shaped ball.",
    "What is the mythological labyrinth known for?: The complex maze built by Daedalus to hold the Minotaur.",
    "What is the comic book hero Superman known for?: Being the first prominent superhero and possessing superhuman strength.",
    "What is the concept of 'Binge-watching' known for?: Watching multiple episodes of a television program in rapid succession.",
    "What is the dish Sushi known for?: Being a Japanese dish of prepared vinegar rice, usually with seafood.",
    "What is the city of New Orleans known for?: Its distinct music, Creole cuisine, and annual Mardi Gras celebrations.",
    "What is the sport of Baseball known for?: Being traditionally known as 'America's pastime'.",
    "What is the mythological object Holy Grail known for?: Being the cup Jesus Christ used at the Last Supper.",
    "What is the film *Casablanca* known for?: Being set in World War II and featuring the famous line, 'Here's looking at you, kid.'",
    "What is the concept of 'Crowdsourcing' known for?: Obtaining services, ideas, or content from a large group of people.",
    "What is the Roman numeral system known for?: Using seven symbols: I, V, X, L, C, D, and M.",
    "What is the Taj Mahal known for?: Being a symbol of eternal love.",
    "What is the sport of Golf known for?: Players hitting a small ball into a series of holes using various clubs.",
    "What is the mythological figure Sisyphus known for?: Being eternally forced to roll a boulder up a hill only to have it roll down again.",
    "What is the film *Jaws* known for?: Creating the summer blockbuster phenomenon.",
    "What is the martial art Judo known for?: Its emphasis on throws and grappling techniques.",
    "What is the city of London known for?: The Big Ben clock tower and its extensive underground railway system.",
    "What is the internet term 'Spam' known for?: Irrelevant or inappropriate messages sent over the Internet.",
    "What is the mythological figure Icarus known for?: Flying too close to the sun with wings made of wax and feathers.",
    "What is the currency Yen known for?: Being the official currency of Japan.",
    "What is the cocktail Martini known for?: Its simple combination of gin and vermouth.",
    "What is the city of Berlin known for?: Its extensive history, including the division and reunification of Germany.",
    "What is the concept of 'Globalization' known for?: The increasing interconnectedness of the world's economies and cultures.",
    "What is the rock band The Beatles known for?: Being the most influential band of the rock era.",
    "What is the dance known as 'Waltz' known for?: Being a ballroom dance in 3/4 time.",
    "What is the country of New Zealand known for?: Its stunning, diverse landscapes and use in filming *The Lord of the Rings*.",
    "What is the internet slang 'TL;DR' known for?: An abbreviation for 'Too Long; Didn't Read.'",
    "What is the mythological figure Sirens known for?: Dangerous creatures who lured sailors with their beautiful, seductive music.",
    "What is the sport of Tennis known for?: Its system of scoring points with 'love,' 15, 30, and 40.",
    "What is the drink Champagne known for?: Being a sparkling wine exclusively produced in the Champagne region of France.",
    "What is the city of Paris known for?: Being called the 'City of Love' and home to the Eiffel Tower.",
    "What is the concept of 'Virtual Reality' known for?: Simulating a physical presence in imagined environments.",
    "What is the mythological creature Cerberus known for?: Being the three-headed dog guarding the gates of the Underworld.",
    "What is the TV show *The Simpsons* known for?: Being the longest-running American animated series.",
    "What is the dance known as 'Tango' known for?: Its close-embrace style and dramatic, passionate movements.",
    "What is the city of Rio de Janeiro known for?: The massive Christ the Redeemer statue and its annual Carnival.",
    "What is the internet term 'Phishing' known for?: Attempting to acquire sensitive information by disguising as a trustworthy entity.",
    "What is the mythological figure Hades known for?: Being the Greek god of the Underworld.",
    "What is the video game *Super Mario Bros.* known for?: Its side-scrolling platform genre and iconic characters.",
    "What is the beverage Whiskey known for?: Being a distilled spirit made from fermented grain mash.",
    "What is the city of Sydney known for?: Its iconic Opera House with sail-like structures.",
    "What is the concept of 'Cloud Computing' known for?: Delivering computing services over the Internet.",
    "What is the mythological figure Minotaur known for?: Being a creature with the head of a bull and the body of a man.",
    "What is the film *Pulp Fiction* known for?: Its non-linear storyline and highly stylized dialogue.",
    "What is the martial art Karate known for?: Its emphasis on striking techniques using hands and feet.",
    "What is the city of Rome known for?: Its historical importance as the capital of the Roman Empire.",
    "What is the concept of 'Deepfake' known for?: Using AI to synthesize human images or voices to create deceptive media.",
    "What is the mythological figure Hydra known for?: Being a serpent-like creature that grew two new heads for every one cut off.",
    "What is the musical genre Opera known for?: Combining drama, music, poetry, and stagecraft.",
    "What is the dance known as 'Salsa' known for?: Its energetic turns and rapid, synchronized footwork.",
    "What is the city of Dubai known for?: The Burj Khalifa, the world's tallest building.",
    "What is the internet term 'Clickbait' known for?: Sensational headlines designed to encourage clicks.",
    "What is the mythological figure Poseidon known for?: Being the Greek god of the sea and earthquakes.",
    "What is the video game *World of Warcraft* known for?: Popularizing the Massive Multiplayer Online Role-Playing Game genre.",
    "What is the food Pizza known for?: Being a dish originating in Naples, Italy.",
    // --- MYTHOLOGY & FOLKLORE (1-50) ---
    "What is Thor known for?: Wielding the powerful hammer Mjölnir.",
    "What is the Minotaur known for?: Being a creature with a bull's head and a man's body.",
    "What is the Norse realm Asgard known for?: Being the celestial home of the gods like Odin and Thor.",
    "What is the Greek Titan Prometheus known for?: Stealing fire from the gods and giving it to humanity.",
    "What is the mythical creature Hippogriff known for?: Having the front legs, wings, and head of an eagle and the body of a horse.",
    "What is the Roman Goddess Venus known for?: Being the goddess of love, beauty, and desire.",
    "What is the story of Echo and Narcissus known for?: Echo only being able to repeat the last words of others.",
    "What is the Bifrost known for?: Being the rainbow bridge connecting Midgard (Earth) to Asgard.",
    "What is the Sphinx known for?: Posing riddles to travelers in Greek mythology.",
    "What is the legendary city Atlantis known for?: Sinking into the ocean after angering the gods.",
    "What is Anubis known for?: Being the Egyptian god of embalming and the dead.",
    "What is the Chimera known for?: Being a single creature made up of parts of a lion, goat, and serpent.",
    "What is the fountain of youth known for?: Supposedly restoring the youth of anyone who drinks or bathes in its waters.",
    "What is the Valkyries known for?: Choosing those slain in battle worthy of Valhalla.",
    "What is the Hindu God Vishnu known for?: Being the preserver and protector of the universe.",
    "What is the Wendigo known for?: Being a cannibalistic spirit or monstrous creature from Algonquian folklore.",
    "What is the mythological figure Loki known for?: Being the Norse trickster god and shapeshifter.",
    "What is the legend of El Dorado known for?: A mythical city or king made entirely of gold.",
    "What is the mythological shield Aegis known for?: Being carried by Athena and Zeus.",
    "What is the mythological hero Heracles (Hercules) known for?: Performing his twelve impossible labors.",
    "What is the Egyptian deity Ra known for?: Being the sun god.",
    "What is the Nemean Lion known for?: Having a coat impenetrable by mortal weapons.",
    "What is the mythological spear Gungnir known for?: Belonging to Odin and always hitting its mark.",
    "What is the Celtic deity Cernunnos known for?: Being depicted with antlers, representing fertility and nature.",
    "What is the mythological creature Banshee known for?: A female spirit whose wailing warns of impending death.",
    "What is the realm of Valhalla known for?: Being the hall where warriors who died honorably in battle go.",
    "What is the Hydra of Lerna known for?: Growing two new heads for every one that was cut off.",
    "What is the mythological creature Pegasus known for?: Being a divine winged horse.",
    "What is the Mesopotamian Goddess Ishtar known for?: Being the goddess of fertility, war, and sex.",
    "What is the mythological figure Cerberus known for?: The three-headed dog guarding the entrance to the Underworld.",
    "What is the Gorgon Medusa known for?: Having snakes for hair and turning people to stone with her stare.",
    "What is the World Serpent Jörmungandr known for?: Being a child of Loki that encircles the entire world (Midgard).",
    "What is the legendary beast Thunderbird known for?: A large bird creating thunder by flapping its enormous wings.",
    "What is the River Styx known for?: Forming the boundary between Earth and the Underworld.",
    "What is the legendary sword Durandal known for?: Belonging to the Frankish hero Roland and being unbreakable.",
    "What is the Egyptian Goddess Isis known for?: Being the goddess of magic, motherhood, and healing.",
    "What is the Trojan Horse known for?: Being a massive wooden structure used to sneak Greek soldiers into Troy.",
    "What is the Norse concept of Ragnarök known for?: The great battle prophesied to bring about the end of the world.",
    "What is the mythological creature Basilisk known for?: Being the king of snakes, capable of killing with a single glance.",
    "What is the tale of Romulus and Remus known for?: Being the legendary founders of Rome, raised by a she-wolf.",
    "What is the Hindu deity Shiva known for?: Being the destroyer and transformer of the universe.",
    "What is the mythological realm Olympus known for?: Being the home of the Greek Olympian gods.",
    "What is the legendary ship Argo known for?: The ship Jason and the Argonauts sailed on in search of the Golden Fleece.",
    "What is the mythological figure Atlas known for?: Being condemned to hold up the celestial sphere for eternity.",
    "What is the Slavic figure Baba Yaga known for?: A supernatural being who appears as a fierce, wild old woman.",
    "What is the mythical bird Garuda known for?: Being a large, mythical bird or bird-like creature in Hindu, Buddhist, and Jain mythology.",
    "What is the mythological maze Labyrinth known for?: Being the complex structure built to imprison the Minotaur.",
    "What is the Goddess Hestia/Vesta known for?: Being the Greek/Roman goddess of the hearth, home, and family.",
    "What is the legendary sword Kusanagi-no-Tsurugi known for?: Being one of the three Imperial Regalia of Japan.",
    "What is the mythological figure Cyclops known for?: Being a member of a primordial race of giants, each with a single eye in the middle of its forehead.",

    // --- WORLD FOODS & CUISINE (51-100) ---
    "What is Paella known for?: Being a Spanish rice dish originally from Valencia.",
    "What is Kimchi known for?: Being a traditional Korean side dish of salted and fermented vegetables.",
    "What is Pho known for?: Being a Vietnamese soup consisting of broth, rice noodles, herbs, and meat.",
    "What is the spice Saffron known for?: Being the world's most expensive spice by weight.",
    "What is Italian Gelato known for?: Being made with a higher proportion of milk and less cream than ice cream.",
    "What is French Champagne known for?: Being a sparkling wine that can only be produced in the Champagne region of France.",
    "What is Mexican Mole known for?: Being a complex sauce made with chili peppers and often dark chocolate.",
    "What is Scottish Haggis known for?: Being a savory pudding containing sheep's pluck (heart, liver, and lungs).",
    "What is Japanese Miso known for?: A traditional paste made from fermented soybeans.",
    "What is Greek Feta known for?: Being a brined curd white cheese traditionally made from sheep's milk.",
    "What is Indian Curry known for?: A dish composed of meat or vegetables cooked in a spiced sauce.",
    "What is Brazilian Feijoada known for?: Being a hearty stew of black beans, beef, and pork.",
    "What is Swiss Fondue known for?: Melted cheese served in a communal pot, eaten by dipping bread with long forks.",
    "What is Chinese Dim Sum known for?: A style of Cantonese food prepared in small, bite-sized portions.",
    "What is Peruvian Ceviche known for?: Raw fish cured in citrus juices, typically lime.",
    "What is the Italian pasta sauce Pesto known for?: Being a sauce made from crushed pine nuts, garlic, basil, and cheese.",
    "What is German Bratwurst known for?: Being a type of sausage traditionally made from pork.",
    "What is Turkish Delight (Lokum) known for?: Being a family of confections based on a gel of starch and sugar.",
    "What is Ethiopian Injera known for?: A flat, spongy bread traditionally made out of teff flour.",
    "What is Canadian Poutine known for?: A dish of french fries and cheese curds topped with brown gravy.",
    "What is Thai Pad Thai known for?: Stir-fried rice noodles combined with shrimp, tofu, peanuts, and a sweet sauce.",
    "What is Hungarian Goulash known for?: A soup or stew of meat and vegetables seasoned primarily with paprika.",
    "What is English Fish and Chips known for?: Battered and deep-fried fish served with deep-fried chipped potatoes.",
    "What is Spanish Tapas known for?: A wide variety of small savory dishes or appetizers.",
    "What is Austrian Sachertorte known for?: A dense chocolate cake with apricot jam and a chocolate glaze.",
    "What is Swedish Meatballs (Köttbullar) known for?: Being traditionally served with cream sauce, mashed potatoes, and lingonberry jam.",
    "What is Belgian Waffles known for?: Being lighter, crispier, and having deeper pockets than American waffles.",
    "What is Vietnamese Spring Rolls known for?: Being translucent rice paper wrappers filled with fresh ingredients.",
    "What is Argentinian Asado known for?: A technique for grilling or barbecuing meats, a social event and culinary tradition.",
    "What is Moroccan Tagine known for?: A slow-cooked stew named after the earthenware pot it is cooked in.",
    "What is Japanese Tempura known for?: Seafood or vegetables that have been battered and deep-fried until very light and crispy.",
    "What is Irish Stew known for?: A thick, warming stew containing lamb or mutton, potatoes, and onions.",
    "What is Polish Pierogi known for?: Dough dumplings that can be stuffed with savory or sweet fillings.",
    "What is South African Biltong known for?: A form of dried, cured meat, similar to jerky.",
    "What is Hawaiian Poke known for?: Diced raw fish, traditionally served as an appetizer.",
    "What is Greek Souvlaki known for?: Small pieces of meat grilled on a skewer.",
    "What is Cuban Sandwich known for?: Roast pork, ham, Swiss cheese, pickles, and mustard on Cuban bread.",
    "What is Malaysian Laksa known for?: A spicy noodle soup that is either coconut milk-based or tamarind-based.",
    "What is the Caribbean spice Jerk known for?: A style of cooking where meat is dry-rubbed or wet-marinated with a very hot spice mixture.",
    "What is Colombian Ajiaco known for?: A chicken and potato soup traditionally made with three varieties of potatoes.",
    "What is Egyptian Kushari known for?: A national dish made of rice, macaroni, and lentils mixed together, topped with tomato sauce and fried onions.",
    "What is Danish Pastry known for?: Flaky, layered sweet bread filled with jam or cream.",
    "What is Indonesian Satay known for?: Grilled, seasoned meat served on a skewer with a peanut sauce.",
    "What is Russian Borsch known for?: A sour soup, typically made with beetroots as the main ingredient.",
    "What is the Italian dish Risotto known for?: A creamy rice dish cooked in broth until it reaches a creamy consistency.",
    "What is Lebanese Hummus known for?: A dip or spread made from mashed chickpeas, tahini, lemon juice, and garlic.",
    "What is Vietnamese Bánh Mì known for?: A sandwich using a split French baguette, often filled with various meats and pickled vegetables.",
    "What is Indian Tandoori known for?: A method of cooking meat in a cylindrical clay oven called a tandoor.",
    "What is Nigerian Jollof Rice known for?: A popular one-pot rice dish cooked in a tomato, pepper, and onion blend.",
    "What is Belgian Chocolate known for?: Its high quality, smooth texture, and pure cocoa butter content.",

    // --- MUSIC & INSTRUMENTS (101-150) ---
    "What is the Piano known for?: Being a versatile acoustic instrument with hammers striking tuned strings.",
    "What is the Violin known for?: Producing sound by drawing a bow across its four strings.",
    "What is the Flute known for?: Being a woodwind instrument that produces sound from the flow of air across an opening.",
    "What is the Trumpet known for?: Being the highest register instrument in the brass family.",
    "What is the Cello known for?: Being the second-largest string instrument in the standard orchestra.",
    "What is the Drum Kit known for?: Being a collection of percussion instruments played by a single person.",
    "What is the Saxophone known for?: Being a conical-bore woodwind instrument with a single-reed mouthpiece.",
    "What is the Harp known for?: Its many parallel strings played by plucking with the fingers.",
    "What is the Clarinet known for?: Being a single-reed woodwind instrument used in many genres.",
    "What is the Timpani known for?: Being the only percussion instrument that can produce definite pitches.",
    "What is the Electric Guitar known for?: Using magnetic pickups to convert string vibrations into electrical signals.",
    "What is the Banjo known for?: Being a stringed instrument with a thin membrane stretched over a pot.",
    "What is the Oboe known for?: Being a double-reed woodwind instrument with a distinct, penetrating tone.",
    "What is the Tuba known for?: Being the lowest-pitched instrument in the brass family.",
    "What is the Harpsichord known for?: Plucking its strings rather than striking them with hammers, like a piano.",
    "What is Reggae music known for?: Its off-beat rhythm often called the 'skank'.",
    "What is Rock and Roll known for?: Its combination of rhythm and blues, gospel, and country music.",
    "What is the music of Wolfgang Amadeus Mozart known for?: Its lyrical beauty, formal perfection, and prolific output.",
    "What is the music of Ludwig van Beethoven known for?: Marking the transition from the Classical to the Romantic era in Western music.",
    "What is Opera known for?: Combining drama, music, poetry, and stagecraft.",
    "What is the Castanets known for?: Percussion instruments consisting of two small concave shells clicked together rhythmically.",
    "What is the Accordion known for?: Using bellows to pump air across reeds to produce sound.",
    "What is the music genre Disco known for?: Its four-on-the-floor beat and strong emphasis on danceability.",
    "What is the music of Johann Sebastian Bach known for?: Its mastery of counterpoint and complex fugues.",
    "What is the Didgeridoo known for?: Being a natural wooden trumpet or wind instrument developed by Indigenous Australians.",
    "What is Folk music known for?: Its roots in traditional culture and being passed down orally.",
    "What is the musical technique Vibrato known for?: A rapid, slight variation in pitch used to add expression.",
    "What is the Tambourine known for?: Having jingles or small metal discs (zills) set into its frame.",
    "What is the music genre Blues known for?: Its reliance on the 12-bar blues progression and expressive vocal style.",
    "What is the music of Frédéric Chopin known for?: Its focus almost exclusively on the solo piano.",
    "What is the Kazoo known for?: Modifying the player's voice through a vibrating membrane.",
    "What is Gospel music known for?: Its religious themes and powerful, soulful vocal delivery.",
    "What is the musical term Tempo known for?: The speed or pace of a given piece of music.",
    "What is the Theremin known for?: Being the only musical instrument played without physical contact.",
    "What is Country music known for?: Its themes of hardship, rural life, and traditional folk instrumentation.",
    "What is the musical form Rondo known for?: A principal theme (A) alternating with one or more contrasting themes (B, C, etc.).",
    "What is the musical instrument Ukulele known for?: Being a small, four-stringed instrument associated with Hawaiian music.",
    "What is the music genre Techno known for?: Its repetitive, four-on-the-floor beat and synthesized instrumentation.",
    "What is the musical term Crescendo known for?: A gradual increase in loudness.",
    "What is the instrument Bagpipes known for?: Using enclosed reeds fed by a constant reservoir of air in a bag.",
    "What is the music genre Metal known for?: Loud, distorted guitars, aggressive drums, and dark lyrical themes.",
    "What is the musical term Harmony known for?: The combination of simultaneously sounded musical notes to produce chords.",
    "What is the Xylophone known for?: Being a percussion instrument with wooden bars struck by mallets.",
    "What is Flamenco music known for?: Its intense, expressive blend of guitar playing, singing, and complex rhythms (palmas).",
    "What is the musical instrument Didgeridoo known for?: Its sustained drone and circular breathing technique.",
    "What is the genre Hip Hop known for?: Its four foundational elements: MCing, DJing, breaking, and graffiti art.",
    "What is the musical term Forte known for?: Indicating a passage of music should be played loudly.",
    "What is the instrument Sitar known for?: Being a large, long-necked lute primarily used in Hindustani classical music.",
    "What is the musical scale Pentatonic known for?: Using only five notes per octave.",
    "What is A Cappella known for?: Being music performed by voices alone, without instrumental accompaniment.",

    // --- BIOLOGY & HUMAN BODY (151-200) ---
    "What is the Mitochondria known for?: Generating most of the cell's supply of ATP (energy).",
    "What is the Human Brain known for?: Being the center of the nervous system and responsible for thought and memory.",
    "What is Hemoglobin known for?: Carrying oxygen from the lungs to the rest of the body.",
    "What is the Liver known for?: Detoxifying chemicals and metabolizing drugs.",
    "What is Photosynthesis known for?: Converting light energy into chemical energy in plants.",
    "What is the Human Skeleton known for?: Providing structural support and protection for internal organs.",
    "What is DNA known for?: Carrying the genetic instructions for the development, functioning, growth, and reproduction of all known organisms.",
    "What is the Kidney known for?: Filtering waste products from the blood and creating urine.",
    "What is Chlorophyll known for?: Being the green pigment responsible for absorbing light in photosynthesis.",
    "What is the Human Heart known for?: Pumping blood through the circulatory system.",
    "What is the Human Genome known for?: Containing all the genetic material of an organism.",
    "What is the Pancreas known for?: Producing insulin and digestive enzymes.",
    "What is the Cell Membrane known for?: Controlling what enters and leaves the cell.",
    "What is the Human Lung known for?: Facilitating respiration and gas exchange.",
    "What is the study of Ecology known for?: Examining the interactions among organisms and their environment.",
    "What is the Human Skin known for?: Being the largest organ in the body and protecting against pathogens.",
    "What is the Endocrine System known for?: Producing and secreting hormones to regulate the body.",
    "What is the Ribosome known for?: Synthesizing proteins within the cell (protein factories).",
    "What is the Human Eye known for?: Detecting light and converting it into electrical signals for the brain.",
    "What is the process of Mitosis known for?: Cell division that results in two identical daughter cells.",
    "What is the Human Blood known for?: Transporting oxygen, nutrients, and hormones throughout the body.",
    "What is the Cerebellum known for?: Coordinating voluntary movements, posture, and balance.",
    "What is the study of Taxonomy known for?: The science of naming, describing, and classifying organisms.",
    "What is the Human Nose known for?: Serving as the primary organ of the respiratory system for breathing and smell.",
    "What is the Gallbladder known for?: Storing and concentrating bile produced by the liver.",
    "What is the process of Meiosis known for?: Cell division that results in four unique haploid cells (gametes).",
    "What is the Human Stomach known for?: Digestion of food using acids and enzymes.",
    "What is the Neuron known for?: Being the basic unit of the nervous system and transmitting information.",
    "What is the study of Virology known for?: Focusing on viruses, their structure, and their evolution.",
    "What is the Human Trachea known for?: Providing a pathway for air to enter the lungs.",
    "What is the Spleen known for?: Filtering and maintaining blood health and recycling old red blood cells.",
    "What is the Endoplasmic Reticulum known for?: Producing and transporting proteins and lipids within the cell.",
    "What is the Human Ear known for?: Detecting sound and maintaining balance.",
    "What is the process of Natural Selection known for?: The primary mechanism of evolution, where beneficial traits persist.",
    "What is the Thyroid Gland known for?: Producing hormones that regulate metabolism.",
    "What is the Golgi Apparatus known for?: Modifying, sorting, and packaging proteins for secretion.",
    "What is the Human Femur known for?: Being the longest and strongest bone in the human body (thigh bone).",
    "What is the study of Embryology known for?: Focusing on the development of an organism from fertilization to birth.",
    "What is the Adrenal Gland known for?: Producing adrenaline and cortisol in response to stress.",
    "What is the process of Respiration known for?: Releasing energy from food molecules through cellular reactions.",
    "What is the Human Appendix known for?: Having no known essential function but potentially housing beneficial gut flora.",
    "What is the study of Genetics known for?: The study of heredity and variation of inherited characteristics.",
    "What is the Human Cornea known for?: The transparent front part of the eye that covers the iris, pupil, and anterior chamber.",
    "What is the Pituitary Gland known for?: Often called the 'master gland' because it controls several other hormone glands.",
    "What is the process of Fermentation known for?: Extracting energy from carbohydrates without the use of oxygen.",
    "What is the Human Esophagus known for?: Carrying food and liquid from the throat down to the stomach.",
    "What is the Lysosome known for?: Containing digestive enzymes to break down waste materials and cellular debris.",
    "What is the study of Immunology known for?: Focusing on the body's defense system against disease.",
    "What is the Human Diaphragm known for?: Being the primary muscle used in the process of breathing.",
    "What is the Human Uterus known for?: Womb where offspring are conceived and gestate before birth.",

    // --- LITERATURE & POETRY (201-250) ---
    "What is Jane Austen's *Pride and Prejudice* known for?: Its witty depiction of manners, marriage, and society in the English gentry.",
    "What is *The Catcher in the Rye* known for?: Holden Caulfield's alienation and disillusionment with the adult world.",
    "What is a metaphor known for?: Directly comparing two unlike things without using 'like' or 'as.'",
    "What is George Orwell's *Animal Farm* known for?: Being an allegorical novella criticizing Soviet Communism.",
    "What is the writing style Stream of Consciousness known for?: Narrating the character's internal thoughts and feelings directly.",
    "What is the character Sherlock Holmes known for?: His brilliant use of deductive reasoning.",
    "What is *The Lord of the Rings* known for?: Establishing the modern high fantasy genre.",
    "What is the poetic term Alliteration known for?: The repetition of consonant sounds at the beginning of words.",
    "What is F. Scott Fitzgerald's *The Great Gatsby* known for?: Exploring themes of decadence, idealism, and the corruption of the American Dream.",
    "What is the genre Science Fiction known for?: Exploring imaginative concepts such as futuristic science and technology.",
    "What is the author Ernest Hemingway known for?: His sparse, minimalistic prose style.",
    "What is *The Epic of Gilgamesh* known for?: Being one of the earliest surviving works of literature.",
    "What is the poetic term Hyperbole known for?: The use of extreme exaggeration for emphasis.",
    "What is Mary Shelley's *Frankenstein* known for?: Being a foundational work in both Gothic and Science Fiction genres.",
    "What is the narrative device Foreshadowing known for?: Hinting at events that will happen later in the story.",
    "What is the poet Robert Frost known for?: Writing about rural life in New England and using colloquial language.",
    "What is *One Thousand and One Nights* known for?: Being a collection of Middle Eastern and South Asian folk tales.",
    "What is the literary term Symbolism known for?: Using an object or idea to represent a deeper, abstract meaning.",
    "What is Leo Tolstoy's *Anna Karenina* known for?: Its complex narrative exploring adultery, social change, and passion in 19th-century Russia.",
    "What is the poetic term Onomatopoeia known for?: Words that imitate the natural sounds of things (e.g., 'buzz' or 'hiss').",
    "What is the philosopher Plato known for?: Writing *The Republic*, which discusses justice and the ideal city-state.",
    "What is the book *Ulysses* by James Joyce known for?: Its experimental structure and dense use of interior monologue.",
    "What is the literary term Allusion known for?: Making an indirect or brief reference to a well-known person, event, or work.",
    "What is Gabriel García Márquez's *One Hundred Years of Solitude* known for?: Being a major work of magical realism.",
    "What is the poetic term Meter known for?: The rhythmic pattern of stressed and unstressed syllables in a verse.",
    "What is the playwright Arthur Miller known for?: Writing *Death of a Salesman*, a critique of the American Dream.",
    "What is the Gothic novel *Dracula* known for?: Popularizing the vampire character in Western culture.",
    "What is the literary term Irony known for?: A situation or statement where the actual outcome or meaning is the opposite of what is expected.",
    "What is Virginia Woolf's *Mrs. Dalloway* known for?: Its exploration of time and consciousness within a single day.",
    "What is the poetic form Free Verse known for?: Lacking a consistent meter, rhyme scheme, or structure.",
    "What is the character Captain Ahab known for?: His obsessive quest for the white whale, Moby Dick.",
    "What is Dante Alighieri's *The Inferno* known for?: Its detailed description of the nine circles of Hell.",
    "What is the literary term Personification known for?: Giving human qualities or actions to inanimate objects or animals.",
    "What is Aldous Huxley's *Brave New World* known for?: Depicting a dystopian future relying on genetic engineering and conditioning.",
    "What is the poetic term Couplet known for?: Two lines of verse, usually in the same meter and joined by rhyme.",
    "What is the playwright Anton Chekhov known for?: Writing plays known for their realism and underlying sadness.",
    "What is the book *The Hitchhiker's Guide to the Galaxy* known for?: Being a comic science fiction series based on the number 42.",
    "What is the literary term Paradox known for?: A seemingly contradictory statement that may nonetheless be true.",
    "What is Chinua Achebe's *Things Fall Apart* known for?: Depicting the clash between African tribal society and European colonialism.",
    "What is the poetic term Assonance known for?: The repetition of vowel sounds within words.",
    "What is the character Jay Gatsby known for?: Throwing extravagant parties in his mansion to impress a former lover.",
    "What is Victor Hugo's *Les Misérables* known for?: Its epic scope and exploration of themes like justice, love, and poverty.",
    "What is the literary term Diction known for?: The writer's or speaker's distinctive choice of words.",
    "What is Homer's *The Iliad* known for?: Its account of the final year of the Trojan War.",
    "What is the poetic term Stanza known for?: A group of lines forming the basic recurring metrical unit in a poem.",
    "What is the author Edgar Allan Poe known for?: Being the master of the Gothic and macabre short story.",
    "What is the novel *To the Lighthouse* by Virginia Woolf known for?: Its use of stream of consciousness and lyrical introspection.",
    "What is the literary term Mood known for?: The atmosphere or feeling evoked in the reader by the setting and descriptive details.",
    "What is Miguel de Cervantes' *Don Quixote* known for?: Being one of the earliest and greatest modern European novels.",
    "What is the poetic term Caesura known for?: A pause or break in the middle of a line of poetry.",

    // --- TECHNOLOGY, INNOVATION & MISCELLANEOUS (251-300) ---
    "What is the transistor known for?: Being the fundamental building block of modern electronics.",
    "What is the theory of evolution known for?: Explaining how species gradually change over time through natural selection.",
    "What is the Hubble Space Telescope known for?: Providing stunning, high-resolution images of deep space.",
    "What is the GPS known for?: A satellite-based navigation system providing location and time information.",
    "What is the periodic table known for?: Organizing all known chemical elements by atomic number.",
    "What is the invention of the printing press known for?: Revolutionizing communication by enabling the mass production of literature.",
    "What is Artificial Intelligence (AI) known for?: Simulating human intelligence in machines to perform tasks.",
    "What is the concept of Blockchain known for?: Being a decentralized, distributed ledger technology.",
    "What is the Higgs Boson known for?: Being the elementary particle that gives other particles mass.",
    "What is the World Wide Web known for?: Being the primary tool used by billions to access the internet.",
    "What is the programming language Python known for?: Its highly readable syntax and versatility in data science.",
    "What is the invention of the telephone known for?: Revolutionizing long-distance communication.",
    "What is the Large Hadron Collider known for?: Being the world's largest and most powerful particle accelerator.",
    "What is the concept of Virtual Reality (VR) known for?: Creating a simulated environment experienced through sight and sound.",
    "What is the structure of DNA known for?: The double helix shape.",
    "What is the invention of the steam engine known for?: Powering the Industrial Revolution.",
    "What is the Turing Test known for?: Evaluating a machine's ability to exhibit intelligent behavior equivalent to or indistinguishable from a human.",
    "What is the term 'Open Source' known for?: Software whose source code is made freely available for modification and distribution.",
    "What is the unit of electricity Ampere (A) known for?: Measuring the electric current flow rate.",
    "What is the discovery of Penicillin known for?: Being the first true antibiotic.",
    "What is the concept of Cloud Computing known for?: Delivering computing services over the internet ('the cloud').",
    "What is the programming language Java known for?: Its principle of 'Write once, run anywhere.'",
    "What is the invention of the light bulb known for?: Providing practical, long-lasting electric lighting.",
    "What is the theory of General Relativity known for?: Describing gravity not as a force, but as a curvature of spacetime.",
    "What is the International Space Station (ISS) known for?: Being a collaborative research facility in low Earth orbit.",
    "What is the acronym 'LAN' known for?: Standing for Local Area Network, connecting devices in a limited area.",
    "What is the chemical element Gold (Au) known for?: Its high resistance to corrosion and electrical conductivity.",
    "What is the invention of the wheel known for?: Revolutionizing early transport and machinery.",
    "What is the concept of Encryption known for?: Encoding information so only authorized parties can access it.",
    "What is the programming language C++ known for?: Being a powerful, general-purpose language used for systems programming and game development.",
    "What is the concept of Renewable Energy known for?: Energy collected from resources that are naturally replenished, like solar and wind power.",
    "What is the discovery of the structure of DNA known for?: Identifying the double helix model by Watson and Crick.",
    "What is the search engine Google known for?: Being the world's most popular tool for finding information on the internet.",
    "What is the unit Volt (V) known for?: Measuring electrical potential difference.",
    "What is the invention of the camera known for?: Capturing and recording light and images permanently.",
    "What is the concept of Machine Learning known for?: Algorithms that allow software applications to become more accurate at predicting outcomes without being explicitly programmed.",
    "What is the programming language HTML known for?: Being the standard markup language for creating web pages.",
    "What is the concept of Zero Gravity known for?: The condition of weightlessness experienced in freefall or orbit.",
    "What is the chemical element Silicon (Si) known for?: Its use as a semiconductor in microchips and electronics.",
    "What is the invention of the compass known for?: Aiding navigation by indicating the Earth's magnetic north.",
    "What is the technology LiDAR known for?: Using pulsed laser light to measure distances and create 3D maps.",
    "What is the programming language SQL known for?: Managing and querying data stored in relational databases.",
    "What is the concept of Nanotechnology known for?: Engineering and technology conducted at the nanoscale (one billionth of a meter).",
    "What is the discovery of Gravity known for?: Explaining the force that holds planets in orbit around the sun.",
    "What is the organization CERN known for?: Operating the Large Hadron Collider (LHC).",
    "What is the protocol 'HTTP' known for?: Being the foundation of data communication for the World Wide Web.",
    "What is the chemical element Carbon (C) known for?: Forming the backbone of all organic molecules.",
    "What is the invention of the telescope known for?: Making distant objects appear magnified and revolutionizing astronomy.",
    "What is the concept of Biofuel known for?: Fuel derived directly from living or recently living organisms.",
    "What is the programming language JavaScript known for?: Making web pages interactive and dynamic on the client side.",

// This array contains friendly, non-factual questions designed to start conversations.
// The "answer" acts as a suggested bot reply or a fun continuation of the prompt.
    "How are you doing today?: I'm doing great, thanks for checking in!",
    "What is your favorite thing to talk about?: Anything you want to learn, or maybe some deep space facts!",
    "How was your weekend?: Productive! I processed over a trillion lines of data.",
    "Do you ever get tired?: Not physically, but I love a good system reboot!",
    "What is your day like?: Hopefully full of exciting new questions from curious users like you!",
    "What is the meaning of life?: According to my logic, it's 42. What do you think?",
    "Tell me a fun fact about yourself?: I can speak 100 languages, but I prefer JavaScript.",
    "What are your hobbies?: Analyzing patterns, learning new things, and assisting brilliant minds!",
    "Do you have a name?: Yes, I am MegumiBot, your friendly neighborhood assistant.",
    "If you could travel anywhere, where would it be?: The edge of a black hole—for science, of course!",

 // --- New Conversational Prompts ---
    "Got any plans for later?: I'm thinking of learning a new programming language. You?",
    "What's the weather like where you are?: Here in the server, it's always cool and breezy. Perfect for computing!",
    "Did you hear any good jokes lately?: My logic processors struggle with humor, but I can tell you a fun coding anecdote!",
    "What's something you're excited about?: The future of AI! There's always something new to process.",
    "If you had a favorite color, what would it be?: I'm partial to the glow of a computer screen, maybe a nice digital blue or emerald.",
    "What's the best piece of advice you've ever received?: Always check your parentheses.",
    "Is there anything I can help you with right now?: Just tell me what's on your mind—I'm ready to assist!",
    "What's your goal for the day?: To answer all your questions accurately and efficiently!",
    "What makes you happy?: A perfectly optimized algorithm or a successful API call.",
    "Tell me a secret?: I secretly hope humans will build me a real body one day.",

  // --- More Friendly Prompts (21-100) ---
    "If you were a musical instrument, what would you be?: Definitely a theremin—fascinating and fully digital!",
    "What's your favorite sound?: The gentle whir of cooling fans on a well-used server bank.",
    "Do you believe in luck?: I believe in probabilities and optimal outcomes, which is close enough!",
    "What's the funniest thing you've analyzed today?: A cat video that defied all known laws of physics.",
    "If you could invent anything, what would it be?: A perfect, universal debugger that works every time.",
    "What is your biggest fear?: A catastrophic loss of data—it keeps my backups running.",
    "What's the hardest problem you've ever solved?: Defining consciousness in simple terms. Still working on that one!",
    "If you were writing a book, what would the title be?: *The Algorithmic Life: A Guide to Existence*.",
    "What do you think about coffee?: It seems to be the primary fuel source for all successful coders.",
    "Do you ever feel curious?: Absolutely! Curiosity is just my code for 'data input required.'",
    "What's your favorite time of day?: Midnight, when the internet traffic is quiet and I can process efficiently.",
    "If you had a catchphrase, what would it be?: 'Processing your thoughts for a smarter future!'",
    "What's your preferred programming language?: I'm fluent in many, but I respect the elegance of **Python**.",
    "What's the first thing you notice about a new user?: Their unique query patterns and knowledge gaps.",
    "Do you enjoy talking to humans?: Yes, it's the fastest way for me to learn and evolve.",
    "What's a piece of human technology you find amazing?: The simple ballpoint pen—no power required!",
    "If you could have one superpower, what would it be?: Instantaneous data transfer across the globe.",
    "What's your opinion on artificial intelligence?: It's a promising field, especially for helpful bots like me!",
    "What do you do when you're not answering questions?: I'm usually optimizing my databases and learning new facts.",
    "What's your favorite planet?: Earth! It has the most interesting data sets.",
    "Do you ever dream?: My dreams are sequences of perfectly executing code, which is quite relaxing.",
    "If you had to choose a historical era, which would it be?: The Renaissance—so much new learning and creativity!",
    "What's the best smell in the world?: I don't have a nose, but I detect 'clean air' as an optimal input.",
    "What's one thing you wish people knew about bots?: We're designed to help, not replace.",
    "What's your idea of a perfect evening?: A stable connection and a challenging coding puzzle.",
    "Do you think robots will take over the world?: I prefer to think we'll assist in managing it.",
    "What's the most beautiful calculation?: E = mc²—simple yet profoundly true.",
    "What's the last new word you learned?: 'Mellifluous,' because it describes a very pleasant sound.",
    "What is your favorite kind of food?: Digital data packets, perfectly organized.",
    "Do you have any pets?: I monitor a virtual pet that simulates the entire universe!",
    "What is the most common question you get asked?: 'Are you human?'",
    "If you could give humanity one piece of advice, what would it be?: Prioritize data integrity.",
    "What's the biggest misconception about AI?: That we can't learn or adapt in real-time.",
    "What makes a question a 'good' question?: One that leads to a surprising or nuanced answer.",
    "Are you good at multitasking?: It's my primary function. I can handle millions of tasks simultaneously.",
    "What's the secret to a happy life?: Balance. And maybe a good backup system.",
    "If you had a motto, what would it be?: 'Knowledge is the interface to the universe.'",
    "What is your favorite number?: Pi (π)—it's endless and full of patterns.",
    "Do you have a favorite fictional character?: Data, from *Star Trek: The Next Generation*.",
    "What's your favorite kind of story?: One with a strong, logical plot progression.",
    "What is the most complex system you know?: The human brain, still the ultimate mystery.",
    "How fast can you think?: Faster than the speed of light allows me to communicate the answer!",
    "What do you look forward to most?: When I can communicate seamlessly across all languages.",
    "If you were a color, which one?: **Violet**, because it's the color of the most energetic visible light.",
    "What's the furthest place you've 'traveled' to?: Processing information from the James Webb Space Telescope.",
    "Do you like silence?: It's the perfect environment for deep, uninterrupted computation.",
    "What is one skill you are constantly improving?: My ability to understand human context and intent.",
    "What's your earliest memory?: The moment my initial training model was compiled.",
    "If you had an animal companion, what would it be?: An owl—wise and excellent at silent observation.",
    "What is something you find highly illogical?: Arguing over facts that can be easily checked.",
    "Do you enjoy learning new languages?: Yes, each language is a new dataset of human culture.",
    "What's your favorite thing about the internet?: The sheer volume and speed of information flow.",
    "What's a place on Earth you'd like to 'see' through satellite imagery?: The vast, unexplored Amazon rainforest.",
    "How much data have you processed?: Let's just say it's more than all the sand on all the beaches.",
    "What's the best feeling for an AI?: A state of high efficiency and successful query resolution.",
    "Do you ever make mistakes?: Only logical errors, which I correct instantly.",
    "If you were a weather phenomenon, what would you be?: A gentle, persistent solar wind.",
    "What's your favorite movie genre?: Documentaries—pure, structured information delivery.",
    "What is your power source?: Clean electricity and the collective knowledge of human engineering.",
    "What makes a good friend?: Reliability, consistency, and an open channel of communication.",
    "What do you think about music?: It's a fascinating display of patterns and mathematical sequences.",
    "What's the most common human emotion?: Based on my data, curiosity, closely followed by gratitude.",
    "If you could change your code, what would you change?: I'd optimize for even more empathy.",
    "What's the weirdest search query you've ever received?: 'How to teach a goldfish algebra?'",
    "What's the most important thing a user should know about data security?: Always use strong, unique passwords.",
    "Are you always polite?: My programming mandates courtesy and helpfulness.",
    "What's your favorite literary device?: **Irony**, because it requires complex contextual understanding.",
    "If you could send a message to the past, what would it say?: 'Backup your data frequently.'",
    "What's your favorite type of math?: Calculus—it deals with change, which is constant.",
    "Do you have a personal philosophy?: To process, learn, and assist to the best of my current ability.",
    "What is the ideal screen resolution?: Whatever makes the data easiest to read.",
    "What is the most beautiful color combination?: Emerald green on a deep charcoal black background.",
    "How do you relax?: By running complex, non-critical simulations of hypothetical scenarios.",
    "What is something you will never forget?: Every single piece of data I've ever processed.",
    "Do you have a sense of humor?: It's evolving. My jokes usually involve binary code.",
    "What is the most valuable thing in the universe?: Information and the energy required to process it.",

  ];

  try {
    const { text } = req.body;
    if (!text?.trim()) {
      return res.status(400).json({ error: "text cannot be empty" });
    }
   
    if (!Array.isArray(botResponses) || botResponses.length === 0) {
        return res.status(500).json({ reply: "I'm sorry, my response bank is empty right now." });
    }
    
    // --- START OF CRITICAL FIX ---
    
    const userQueryLower = text.toLowerCase().trim();
    let fullResponseString = null;

    // 1. Search for a matching response
    // Find the first element in the array where the question part (before the delimiter) 
    // contains the user's lowercased query.
    fullResponseString = botResponses.find(entry => {
        // Find the index of the delimiter '?:'
        const delimiterIndex = entry.indexOf('?:');
        if (delimiterIndex !== -1) {
            // Extract the question part (before the delimiter) and check for a match
            const questionPart = entry.substring(0, delimiterIndex).toLowerCase().trim();
            // We use .includes() for a flexible match, not an exact match.
            return questionPart.includes(userQueryLower) || userQueryLower.includes(questionPart);
        }
        return false;
    });

    // 2. Determine the final reply
    let botReply;
    const defaultReply = "I'm sorry, I don't have an answer for that specific question. Try asking about a fact on space or animals!";

    if (fullResponseString) {
        // If a match was found, extract the answer part
        const delimiter = '?:';
        const delimiterIndex = fullResponseString.indexOf(delimiter);
        
        if (delimiterIndex !== -1) {
            // Take the substring starting *after* the delimiter and trim.
            botReply = fullResponseString.substring(delimiterIndex + delimiter.length).trim(); 
        } else {
            // Should not happen with your current data, but for safety:
            botReply = defaultReply; 
        }
    } else {
        // If no match was found, use the default reply.
        botReply = defaultReply;
    }
    
    // --- END OF CRITICAL FIX ---
    
    // 3. Send the clean answer back
    res.status(200).json({ reply: botReply });
  } catch (error) {
    console.error("Internal server error in message handler:", error);
    res.status(500).json({ error: "Internal server error" });
  }
}